name = "social-media-platform"
type = "javascript"  # Or "webpack" if you use webpack explicitly

[build]
command = "npm run build"  # Your build command (this triggers the Docker build)
pages_build_output_dir = "build"  # The directory where your build command outputs files
